name: Release Drafter

on:
  push:
    paths:
      - update_log.json

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate release log
        run: |
          RELEASE_APK_VERSION=`python release.py`
          echo "RELEASE_APK_VERSION=$RELEASE_APK_VERSION" >> $GITHUB_ENV

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          body_path: releaselog_cache.txt
          files: apk/warbanner-release.apk
          tag_name: ${{ env.RELEASE_APK_VERSION }}
          name: warbanner v${{ env.RELEASE_APK_VERSION }}
